name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"     # every 12 hours
  workflow_dispatch:            # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Landon-Bragg
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago
          plugin_lines: no
